//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEUprava.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKorisnikLicneKarte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKorisnikLicneKarte()
        {
            this.tblLicnaKartas = new HashSet<tblLicnaKarta>();
        }
    
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string Jmbg { get; set; }
        public string Pol { get; set; }
        public string Adresa { get; set; }
        public string Mesto { get; set; }
        public int Potpis { get; set; }
        public int Otisak { get; set; }
        public int Slika { get; set; }
    
        public virtual tblOtisak tblOtisak { get; set; }
        public virtual tblPotpi tblPotpi { get; set; }
        public virtual tblSlika tblSlika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLicnaKarta> tblLicnaKartas { get; set; }
    }
}
