//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEUprava.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class tblKorisnikLicneKarte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKorisnikLicneKarte()
        {
            this.tblLicnaKartas = new HashSet<tblLicnaKarta>();
        }
        public int Id { get; set; }
        [Required(ErrorMessage = "Ime je obavezno polje.")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Prezime je obavezno polje.")]
        public string Prezime { get; set; }
        [DisplayName("Datum rođenja")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime DatumRodjenja { get; set; }
        [DisplayName("JMBG")]
        [Required(ErrorMessage = "JMBG je obavezno polje.")]
        [StringLength(13, ErrorMessage = "JMBG treba da sastoji od 13 cifara.", MinimumLength = 13)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "JMBG treba da sastoji od 13 cifara.")]
        public string Jmbg { get; set; }
        [Required(ErrorMessage = "Pol je obavezno polje.")]
        public string Pol { get; set; }
        [Required(ErrorMessage = "Adresa je obavezno polje.")]
        public string Adresa { get; set; }
        [Required(ErrorMessage = "Mesto je obavezno polje.")]
        public string Mesto { get; set; }
        public HttpPostedFileBase SlikaKorisnika { get; set; }
        public HttpPostedFileBase OtisakKorisnika { get; set; }
        public HttpPostedFileBase PotpisKorisnika { get; set; }
        public string Fullname { get { return string.Format("{0} {1}", Ime, Prezime); } }
        public int Potpis { get; set; }
        public int Otisak { get; set; }
        public int Slika { get; set; }
        public virtual tblOtisak tblOtisak { get; set; }
        public virtual tblPotpi tblPotpi { get; set; }
        public virtual tblSlika tblSlika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLicnaKarta> tblLicnaKartas { get; set; }
    }
}
