//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEUprava.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblKorisnikAplikacije
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKorisnikAplikacije()
        {
            this.tblLicnaKartas = new HashSet<tblLicnaKarta>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Ime je obavezno polje.")]
        public string Ime { get; set; }
        [Required(ErrorMessage = "Prezime je obavezno polje.")]
        public string Prezime { get; set; }
        [Required(ErrorMessage = "Pol je obavezno polje.")]
        public string Pol { get; set; }
        [DisplayName("JMBG")]
        [Required(ErrorMessage = "JMBG je obavezno polje.")]
        [StringLength(13, ErrorMessage = "JMBG treba da sastoji od 13 cifara.", MinimumLength = 13)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "JMBG treba da sastoji od 13 cifara.")]
        public string Jmbg { get; set; }
        [Required(ErrorMessage = "Adresa je obavezno polje.")]
        public string Adresa { get; set; }
        [Required(ErrorMessage = "Mesto je obavezno polje.")]
        public string Mesto { get; set; }
        [DisplayName("Broj telefona")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "Broj telefona može da sadrži samo brojeve.")]
        [Required(ErrorMessage = "Broj telefona je obavezno polje")]
        public string BrojTelefona { get; set; }
        [DisplayName("Datum rođenja")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public System.DateTime DatumRodjenja { get; set; }
        [Required(ErrorMessage = "Email je obavezan.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Email is not valid")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Lozinka je obavezna.")]
        public string Password { get; set; }
        [Required(ErrorMessage = "Potrvrda lozinke je obavezna.")]
        public string ConfirmPassword { get; set; }
        public int Poslodavac { get; set; }
        public virtual tblIzdavalac tblIzdavalac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLicnaKarta> tblLicnaKartas { get; set; }
    }
}
