//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEUprava.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKorisnikLicneKarte
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public System.DateTime DatumRodjenja { get; set; }
        public string Jmbg { get; set; }
        public string Pol { get; set; }
        public string Adresa { get; set; }
        public string Mesto { get; set; }
        public int Potpis { get; set; }
        public int Otisak { get; set; }
        public int Slika { get; set; }
        public byte[] Expr1 { get; set; }
        public byte[] Expr2 { get; set; }
        public byte[] Expr3 { get; set; }
    }
}
