//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEUprava.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwKorisnikAplikacije
    {
        public byte[] Naziv { get; set; }
        public int Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
        public string Expr4 { get; set; }
        public string Expr5 { get; set; }
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Pol { get; set; }
        public string Jmbg { get; set; }
        public string Adresa { get; set; }
        public string Mesto { get; set; }
        public string BrojTelefona { get; set; }
        public Nullable<System.DateTime> DatumRodjenja { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Poslodavac { get; set; }
    }
}
