//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCEUprava.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLicnaKarta
    {
        public int Id { get; set; }
        public string RegistarskiBroj { get; set; }
        public System.DateTime DatumIzdavanja { get; set; }
        public System.DateTime DatumIsteka { get; set; }
        public int KorisnikAplikacije { get; set; }
        public int KorisnikLicneKarte { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
    }
}
